= Schedule_Sharing REST API
김동희,송인철;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[resources]]
= 리소스

[[resources-index]]
== 인덱스
[[resources-member]]
== Member
[[resources-member-signup]]
=== 회원가입
operation::member-signup[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
[[resources-member-checkEmail]]
=== 이메일 중복 체크
operation::member-checkEmail[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
=== 로그인 성공
[[resources-member-login]]
operation::member-login[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
=== 로그인 실패
[[resources-member-login-fail]]
operation::member-login-fail[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-club]]
== Club
[[resources-club-create]]
=== 모임 생성
operation::club-create[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
[[resources-club-invite]]
=== 모임 초대
operation::club-invite[snippets='request-fields,path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']
[[resources-club-delete]]
=== 모임 삭제
operation::club-delete[snippets='path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']