= Schedule_Sharing REST API
김동희,송인철;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[resources]]
= 리소스

[[resources-index]]
== 인덱스
[[resources-member]]
== Member
[[resources-member-signup]]
=== 회원가입
operation::member-signup[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
[[resources-member-checkEmail]]
=== 이메일 중복 체크
operation::member-checkEmail[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
=== 로그인 성공
[[resources-member-login]]
operation::member-login[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']
=== 로그인 실패
[[resources-member-login-fail]]
operation::member-login-fail[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-club]]
== Club

[[resources-club-create]]
=== 클럽 생성
operation::club-create[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-club-invite]]
=== 클럽 초대
operation::club-invite[snippets='request-fields,path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-club-getOne]]
=== 클럽 조회(클럽장)
operation::club-getOne[snippets='path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-club-update]]
=== 클럽 수정(클럽장)
operation::club-update[snippets='path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-club-delete]]
=== 클럽 삭제(클럽장)
operation::club-delete[snippets='path-parameters,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-clubSchedule]]
== ClubSchedule

[[resources-clubSchedule-create]]
=== 클럽스케줄 생성
operation::clubSchedule-create[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-clubSchedule-getOne]]
=== 클럽스케줄 조회(작성자)
operation::clubSchedule-getOne[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-clubSchedule-update]]
=== 클럽스케줄 수정(작성자)
operation::clubSchedule-update[snippets='request-fields,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-clubSchedule-delete]]
=== 클럽스케줄 삭제(작성자)
operation::clubSchedule-delete[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']
